# Generated by Django 4.1.7 on 2023-03-21 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('current_floor', models.IntegerField(default=0)),
                ('destination_floor', models.IntegerField(default=0)),
                ('direction', models.CharField(default='stop', max_length=10)),
                ('status', models.CharField(default='working', max_length=20)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(default=0)),
                ('direction', models.CharField(default='up', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('elevator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
        ),
    ]
