# Generated by Django 4.1.7 on 2023-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='elevator_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
