# Generated by Django 4.1.7 on 2023-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_elevator_elevator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_floor',
            field=models.IntegerField(default=0),
        ),
    ]
